#%RAML 1.0 NamedExample

---
order:
  sourceOrderId: '345678932'
  source: G
  type: ''
  creationChannel: ''
  distributionChannel: ''
  countryPlacedFrom: US
  currency: USD
  orderDateTime: yyyy-mm-ddThh:mm:ss
  receivedDateTime: yyyy-mm-ddThh:mm:ss
  requestedDeliveryDate: ''
  salesLegalEntity: BPCS
  language: EN-US
  partyId: 0015f00000CtvaUAAR
  amount:
  - type: SHP
    value: '0.0'
  alternateIdentifier:
  - systemIdentifier: distPurchaseOrderNumber
    systemCode: DDEF1234567
  lineItem:
  - lineItemIdentifier: ''
    sourceLineItemNumber: ''
    quantity: 0
    status: new
    createdDateTime: yyyy-mm-ddThh:mm:ss
    fulfillmentEntity: VENDOR
    product:
      productIdentifier: ''
      sourceSytemProductId: ''
  